name: 'PR Reading Time'
description: 'Automatically estimates and displays reading/review time for pull requests'
author: 'micahstubbs'
branding:
  icon: 'clock'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}

  update-description:
    description: 'Whether to update PR description with reading time'
    required: false
    default: 'true'

  comment-instead:
    description: 'Post as comment instead of updating description'
    required: false
    default: 'false'

outputs:
  reading-time:
    description: 'The calculated reading time'
    value: ${{ steps.calculate.outputs.time }}

  total-changes:
    description: 'Total lines changed'
    value: ${{ steps.calculate.outputs.changes }}

runs:
  using: 'composite'
  steps:
    - name: Checkout Action Code
      uses: actions/checkout@v4
      with:
        repository: micahstubbs/pr-reading-time
        path: .pr-reading-time
        sparse-checkout: scripts
        sparse-checkout-cone-mode: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Get PR Stats
      id: pr-stats
      shell: bash
      run: |
        gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
          --jq '.additions, .deletions, .changed_files' > /tmp/pr-stats.txt

        additions=$(sed -n '1p' /tmp/pr-stats.txt)
        deletions=$(sed -n '2p' /tmp/pr-stats.txt)
        changed_files=$(sed -n '3p' /tmp/pr-stats.txt)

        echo "additions=$additions" >> $GITHUB_OUTPUT
        echo "deletions=$deletions" >> $GITHUB_OUTPUT
        echo "changed_files=$changed_files" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Get File Details
      shell: bash
      run: |
        gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files \
          --paginate \
          --jq '.[] | "\(.filename):\(.changes):\(.additions):\(.deletions)"' > /tmp/file-changes.txt
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Calculate Reading Time
      id: calculate
      shell: bash
      run: |
        cd .pr-reading-time
        node scripts/calculate-reading-time.js \
          --additions "${{ steps.pr-stats.outputs.additions }}" \
          --deletions "${{ steps.pr-stats.outputs.deletions }}" \
          --files "${{ steps.pr-stats.outputs.changed_files }}" \
          --file-details /tmp/file-changes.txt

        reading_time=$(cat reading-time.txt)
        total_changes=$(({{ steps.pr-stats.outputs.additions }} + {{ steps.pr-stats.outputs.deletions }}))

        echo "time=$reading_time" >> $GITHUB_OUTPUT
        echo "changes=$total_changes" >> $GITHUB_OUTPUT

    - name: Update PR Description
      if: inputs.update-description == 'true' && inputs.comment-instead == 'false'
      shell: bash
      run: |
        cd .pr-reading-time
        reading_time="${{ steps.calculate.outputs.time }}"

        gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
          --jq '.body // ""' > /tmp/current-description.txt

        node scripts/update-pr-description.js \
          --time "$reading_time" \
          --description-file /tmp/current-description.txt > /tmp/new-description.txt

        gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
          --method PATCH \
          --field body="$(cat /tmp/new-description.txt)"

        echo "✅ Updated PR description with reading time: $reading_time"
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Post Comment
      if: inputs.comment-instead == 'true'
      shell: bash
      run: |
        reading_time="${{ steps.calculate.outputs.time }}"

        gh pr comment ${{ github.event.pull_request.number }} \
          --body "## 📖 PR Reading Time

        Review time: $reading_time

        This is based on:
        - 📝 ${{ steps.pr-stats.outputs.changed_files }} files changed
        - ➕ ${{ steps.pr-stats.outputs.additions }} additions
        - ➖ ${{ steps.pr-stats.outputs.deletions }} deletions" \
          --repo ${{ github.repository }}

        echo "✅ Posted comment with reading time: $reading_time"
      env:
        GH_TOKEN: ${{ inputs.github-token }}